apiVersion: apps/v1
kind: Deployment 

metadata: 
   name: flask-app-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask-app-container
          image: samiaaax/webapp-devops:1.0
          ports:
          - containerPort: 5001
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # Port for internal communication within the cluster
      targetPort: 5001 # Port exposed by your container
  type: ClusterIP