# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
<<<<<<< HEAD
<<<<<<< HEAD
- secrets-feature
=======
- main
>>>>>>> parent of f79caf6 (updates repo with files needed for students)
=======
- main
>>>>>>> parent of f79caf6 (updates repo with files needed for students)

pool:
  vmImage: ubuntu-latest

steps:
<<<<<<< HEAD
<<<<<<< HEAD
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
=======
=======
>>>>>>> parent of f79caf6 (updates repo with files needed for students)
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mayaaiuga/devops-web-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'aks-service-connection'
    azureResourceGroup: 'aks-rg'
    kubernetesCluster: 'aks-demo'
<<<<<<< HEAD
    manifests: 'deployment.yaml'
>>>>>>> parent of f79caf6 (updates repo with files needed for students)
=======
    manifests: 'deployment.yaml'
>>>>>>> parent of f79caf6 (updates repo with files needed for students)
