# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'chyjuls/web-delivery'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'


- task: KubernetesManifest@1
  inputs:
      action: 'deploy'
      connectionType: 'azureResourceManager'
      azureSubscriptionConnection: 'Chinyere Ugorji DevOps(9b6d204f-381b-4e09-8ce3-b10cfc7a5a4f)'
      azureResourceGroup: 'networking-resource-group'
      kubernetesCluster: 'terraform-aks-cluster'
      manifests: 'application-manifest.yaml'

