# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Azure devops webapps service connection'  # Replace with your Docker Hub service connection name
      repository: 'nasiima/web-app-devops-project'  # Replace with your Docker Hub repository name
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.SourceBranchName)_$(Build.BuildId)

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run additional tasks'


