# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main


pool:
  vmImage: ubuntu-latest
  
  
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'serviceConnection'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- script: |
    ls -R /home/vsts/work/1/s/venv
  displayName: 'List Virtual Environment Contents'

    
- script: |
    source /home/vsts/work/1/s/venv/bin/activate
  displayName: 'Activate Python Virtual Environment'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'azureConnection'
    azureResourceGroup: 'my-resource-group'
    kubernetesCluster: 'my-resource-group'
    manifests: 'application-manifest.yaml'
